#!/usr/bin/env python3
"""Generate brand/MANIFEST.json from the actual asset bytes: per file the size,
sha256, and (for PNGs) the real pixel dimensions parsed from the IHDR chunk.
Dependency-free (no Pillow). Run after adding/replacing an asset.

Usage: python3 scripts/build_manifest.py [--check]
  (no arg)  write brand/MANIFEST.json
  --check   fail if it would change (drift = stale manifest)
"""
from __future__ import annotations

import hashlib
import json
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / "brand"
_PNG_SIG = b"\x89PNG\r\n\x1a\n"


def png_size(data: bytes) -> tuple[int, int]:
    if data[:8] != _PNG_SIG or data[12:16] != b"IHDR":
        raise ValueError("not a PNG / no IHDR")
    w, h = struct.unpack(">II", data[16:24])
    return w, h


def build() -> dict:
    files = {}
    for p in sorted(BRAND.rglob("*")):
        if p.is_dir() or p.name == "MANIFEST.json":
            continue
        data = p.read_bytes()
        rel = p.relative_to(BRAND).as_posix()
        entry = {"bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()}
        if p.suffix == ".png":
            w, h = png_size(data)
            entry["px"] = f"{w}x{h}"
        files[rel] = entry
    return {
        "_note": "Brand/asset integrity manifest (generated by scripts/build_manifest.py). "
                 "Consumed by web-core's PWA/error-kit (icon contract) + the fleet.",
        "asset_count": len(files),
        "files": files,
    }


def render() -> str:
    return json.dumps(build(), ensure_ascii=False, indent=2) + "\n"


def main(argv: list[str]) -> int:
    out = BRAND / "MANIFEST.json"
    rendered = render()
    if "--check" in argv:
        cur = out.read_text(encoding="utf-8") if out.is_file() else ""
        if cur != rendered:
            print("[assets] FAIL — MANIFEST.json is stale; run: make manifest")
            return 1
        print("[assets] MANIFEST.json up to date")
        return 0
    out.write_text(rendered, encoding="utf-8")
    print(f"[assets] wrote {out.relative_to(ROOT)} ({build()['asset_count']} assets)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
